### ISSUE TITLE
consider handling of namespaces in completions

### ISSUE THREAD

**Issue by jbfaden** [mbien/xpath-util#3]
With the GeoTracker app I get a kml file with nodes like /kml/Document/Placemark/MultiTrack/gx:Track

The completions offer "gx:Track", but when I accept this completion, I get the error "Prefix must resolve to a namespace: gx".  I can manually remove the "gx:" prefix, but it seems that if it won't work, that it shouldn't offered as a completion.

**Comment by jbfaden** [comment]
See https://jfaden.net/~jbf/autoplot/data/xml/kml/GeoTracker.kml.

**Comment by mbien** [comment]
hi @jbfaden, yeah I vaguely remember that there were several issues with namespaces. But before changing anything it would be good to add tests first. This plugin is fairly old I only cleaned it up recently so that it is compatible with modern NB.

**Comment by jbfaden** [comment]
This is a wonderful tool which I've been seeking for a long time.  Let me know if I could help.  It's been years since I've worked on a Netbeans plugin, but I enjoyed it and I still use many of the plugins I wrote 15 years ago. (I wrote nbexpose, https://github.com/jbfaden/nbexpose, for example.)  I'd love to get back into it.

**Comment by mbien** [comment]
sorry for the delay - I didn't forget :)

I think this should be now fixed. It should work fine with two limitations:
 - the namespaces must be set globally
 - if there is a namespace set, there also needs to be a default namespace set

tested it with the file you provided and it worked.

The reason why this is tricky to implement is because `javax.xml.namespace.NamespaceContext` is basically a simple key value map. Whenever a XPath wants to know a namespace during evaluation it asks this context but the context itself doesn't really know where the XPath is in the document while its evaluating. -> chicken and egg problem.

**Comment by mbien** [comment]
uploaded a release here to github. Can take a little bit till it shows up in the update center.
